apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: college-demo
data:
  zookeeper_client_port: "2181"
  zookeeper_tick_time: "2000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: college-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - name: zookeeper-container
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: zookeeper_client_port
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: zookeeper_tick_time
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: college-demo
spec:
  selector:
    name: zookeeper
  ports:
    - port: 22181
      targetPort: 2181
