apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: college-demo
data:
  kafka_broker_id: "1"
  kafka_zookeeper_connect: "zookeeper-service:2181"
  kafka_advertised_listeners: "PLAINTEXT://kafka-service:9092,PLAINTEXT_HOST://localhost:29092"
  kafka_listener_security_protocol_map: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  kafka_inter_broker_listener_name: "PLAINTEXT"
  kafka_offsets_topic_replication_factor: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: college-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:latest
          ports:
            - name: first
              containerPort: 29092
            - name: second
              containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_broker_id
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_zookeeper_connect
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_advertised_listeners
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_listener_security_protocol_map
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_inter_broker_listener_name
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: kafka_offsets_topic_replication_factor
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: college-demo
spec:
  selector:
    name: kafka
  ports:
    - name: f-port
      port: 29092
      targetPort: 29092
    - name: s-port
      port: 9092
      targetPort: 9092
