apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: college-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logstash
  template:
    metadata:
      labels:
        name: logstash
    spec:
      containers:
        - name: logstash-container
          image: logstash:8.4.1
          command: ["logstash"]
          args: ["-f", "/etc/logstash/conf.d/logstash.conf"]
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: college-demo
spec:
  selector:
    name: logstash
  ports:
    - port: 5000
      targetPort: 5000
