apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: college-demo
data:
  server_name: "kibana-container"
  elasticsearch_hosts: "http://elasticsearch-service:9200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: college-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kibana
  template:
    metadata:
      labels:
        name: kibana
    spec:
      containers:
        - name: kibana-container
          image: kibana:8.4.1
          ports:
            - containerPort: 5601
          env:
            - name: SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: server_name
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: elasticsearch_hosts
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: college-demo
spec:
  selector:
    name: kibana
  type: LoadBalancer
  ports:
    - port: 5601
      targetPort: 5601
