apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: college-demo
data:
  mongo_initdb_root_username: "root"
  mongo_initdb_root_password: "rootpassword"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: college-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
        - name: mongo-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo_initdb_root_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo_initdb_root_password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: college-demo
spec:
  selector:
    name: mongo
  ports:
    - port: 27017
      targetPort: 27017
