apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: college-demo
data:
  postgres_db: "academy"
  postgres_user: "ilya"
  postgres_password: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: college-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: college-demo
spec:
  selector:
    name: postgres
  ports:
    - port: 5432
      targetPort: 5432
